name: Java Tests

on:
  push:
    paths:
      - '**.java'
  pull_request:
    paths:
      - '**.java'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: Run Java tests
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: corretto

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.12.1
          cache-read-only: false

      - name: Run tests
        run: sh scripts/test.sh
